### PR TITLE
added tests

### PR DESCRIPTION
**Pull request by aouame**
Capture
Capture2
The tests only check if the block is displayed. I did not manage to get to the text.

### CODE REVIEW

**Review by lucasrlt — APPROVED** [review]
It's great, nice job ! Everything looks good to me

**Review by ToufiPF — DISMISSED** [review]
Sorry I had to make this string static, it was gnawing at me ^^'.
Other than that, great work!

**Review by Mortadha-abderrhim — APPROVED** [review]
Seems Fine. GJ

**Review by amomo25 — APPROVED** [review]
Everything looks great to me

**Pull request merged**
