### PR TITLE
ContentFragment & StartTourActivity

### PR DESCRIPTION
**Pull request by ToufiPF**
Note: I apologize in advance, it's quite a big PR because it was in fact supposed to be 2 smaller separated PRs, but I messed up with git and one branch got corrupted, so I had to move everything on this PR.

Feature1: ContentFragment.
I basically moved the code that was creating the BlockFragments depending on the content of an experience, from ExperienceActivity to a new fragment : ContentFragment. It allows other activities to reuse its functionalities more easily, it's more flexible because we don't have to worry about the actionbars of ExperienceActivity in another activity that don't need them.

Feature2: StartTourActivity
When starting a tour, the user is now redirected to a screen that tells them to go to the start location of the tour. Once they are at the correct location (in a radius of 30m), the screen disappears by itself and the MapboxActivity is started.
**I also added a backdoor to start the tour even when not at the right location, for convenience. It's totally invisible and there's no animation when clicking on it. It's at the top right corner of the activity, as shown in red in the screenshot below.**
I designed the backdoor to be easily disableable when releasing the production version of the app (boolean 'backdoorEnabled')

### CODE REVIEW

**Review by lucasrlt — APPROVED** [review]
Quite frustrating to find nothing to fix on such a big PR :disappointed: 
Refactoring the experience activity content into a content fragment is a really good idea, it will be useful also later on for the AR activity since we has problems with the title bar

**Review by lucasrlt — APPROVED** [review]
Quite frustrating to find nothing to fix on such a big PR :disappointed: 
Refactoring the experience activity content into a content fragment is a really good idea, it will be useful also later on for the AR activity since we has problems with the title bar

**Review by hadiyahya11 — APPROVED** [review]
Nice idea refactoring the content fragment ! Gj on this PR

**Review by aouame — DISMISSED** [review]
Great pr and clean code.

**Review by hadiyahya11 — APPROVED** [review]

**Review by aouame — APPROVED** [review]

**Pull request merged**
